#!/bin/bash
#
#       /etc/rc.d/init.d/rcube2pam
#
# Starts the rcube2pam daemon
#
# chkconfig: - 65 35
# description: rouncube password plugin secure async backend
# processname: rcube2pam
# config: 
# pidfile: /var/run/rcube2pam/process.pid

### BEGIN INIT INFO
# Provides: rcube2pam
# Required-Start: $local_fs $network
# Required-Stop: $local_fs $network
# Should-Start: $remote_fs 
# Should-Stop: $remote_fs
# Default-Start: 
# Default-Stop: 0 1 2 3 4 5 6
# Short-Description: rouncube password plugin secure async backend
# Description: rouncube password plugin secure async backend
### END INIT INFO


# Source function library.
. /etc/init.d/functions


RETVAL=0
prog="rcube2pam"
exec="/sbin/rcube2pam"
pidfile="/var/run/rcube2pam/process.pid"
lockfile="/var/lock/subsys/rcube2pam"

start() {
        [ $UID -eq 0 ] || exit 4
        [ -x $exec ] || exit 5
        [ -f $config ] || exit 6

        echo -n $"Starting $prog: "
        /sbin/rcube2pam &  success
        RETVAL=$?
        [ $RETVAL -eq 0 ] && touch  $lockfile
        echo
        return $RETVAL
}

stop() {
        [ $UID -eq 0 ] || exit 4
        echo -n $"Stopping $prog: "
        killproc -p $pidfile $exec
        RETVAL=$?
        [ $RETVAL -eq 0 ] && rm -f $lockfile
        echo
}

reload() {
        [ $UID -eq 0 ] || exit 4
        echo -n $"Reloading $prog: "
        killproc -p $pidfile $exec -HUP
        RETVAL=$?
        echo
}

#
#       See how we were called.
#
case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  reload)
        reload
        ;;
  force-reload|restart)
        stop
        sleep 1
        start
        RETVAL=$?
        ;;
  condrestart|try-restart)
        if [ -f $lockfile ]; then
            stop
            sleep 3
            start
        fi
        ;;
  status)
        status -p $pidfile $exec
        RETVAL=$?
        ;;
  *)
        echo $"Usage: $0 {condrestart|try-restart|start|stop|restart|reload|force-reload|status}"
        RETVAL=2
        [ "$1" = 'usage' ] && RETVAL=0
esac

exit $RETVAL

